### ISSUE TITLE
Identify record linking

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1167]
Some fields in the records are `$ref`s pointing to different records. This is the list of all such fields in the schemas, and how they are currently produced.

FYI, the list of fields were produced from the various top-level schemas by using the following `jq` command:
```
jq 'paths(objects) | select(.[-1] == "$ref") | map(select(. != "properties" and . != "items")) | join(".")' $SCHEMA
```
## all schemas

* [ ] `deleted_records.$ref`: **legacy merger** (#1252)
* [ ] `new_record.$ref`: **legacy merger** (#1252)
* [ ] `self.$ref`: dojson, really needed? (see #1251)

## hep.json

* [x] `accelerator_experiments.record.$ref`: **legacy XME** and manually in editor
* [ ] `authors.affiliations.record.$ref`: **legacy XME** (#1260)
* [x] `authors.record.$ref`: **legacy XME**, disambiguation and claiming
* [x] `collaborations.record.$ref`: **legacy XME** (not needed for now, as links produce searches)
* [x] `publication_info.conference_record.$ref`: **legacy XME** and hep based on `cnum`: https://github.com/inspirehep/inspirehep/blob/22f728bead6b016a5b9326e3a5d2e45f91e0e845/backend/inspirehep/records/api/literature.py#L141-L153
* [x] `publication_info.journal_record.$ref`: next when normalizing journal titles in workflow: https://github.com/inspirehep/inspire-next/blob/64663d93b0d3f1bd5c203fedeaff06cc7e1e9b01/inspirehep/modules/workflows/tasks/actions.py#L523-L558
* [ ] `publication_info.parent_record.$ref`: manually, not possible in editor currently (#1255)
* [ ] `record_affiliations.record.$ref`: **legacy XME**
* [ ] `references.record.$ref`: **legacy XME** (#1254)
* [ ] `related_records.record.$ref`: manually, not possible in editor currently (#1255)
* [x] `thesis_info.institutions.record.$ref`: **legacy XME** and manually in editor

## authors.json

* [x] `advisors.record.$ref`: manually only (needs disambiguation for automating), this is why we display a link to a search on the UI instead of a link to the record
* [x] `positions.record.$ref`: **legacy XME** (should be done manually in the submission form/editor)
* [x] `project_membership.record.$ref`: **legacy XME** (should be done manually in the submission form/editor)

## conferences.json

* [x] `contact_details.record.$ref`: manually in submission form

## experiments.json

* [ ] `accelerator.record.$ref`: manually, should be taken from value in editor
* [ ] `collaboration.record.$ref`: manually, should be taken from value in editor
* [ ] `institutions.record.$ref`: manually, should be taken from value in editor
* [ ] `related_records.record.$ref`: manually, not possible in editor currently (#1255)

## institutions.json

* [ ] `related_records.record.$ref`: manually, not possible in editor currently (#1255)

## jobs.json

* [x] `accelerator_experiments.record.$ref`: manually through submission form
* [x] `contact_details.record.$ref`: manually through submission form
* [x] `institutions.record.$ref`: manually through submission form

## journals.json

* [ ] `related_records.record.$ref`: manually, not possible in editor currently (#1255)
