### ISSUE TITLE
Legacy switchoff checklist

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1840]
This is a checklist of things that need to be done in the process of switching off legacy. This assumes all required features have been implemented, and the only thing required is performing the following operational steps.

Before switching off legacy:
- [x] make a last complete dump of all legacy records
- [ ] remigrate labs from this full dump
- [ ] stop curation on legacy
- [ ] manually harvest once with all the crawlers that will be enabled on labs since the last legacy run date, to initialize the hepcrawl `last_run` timestamps
- [ ] disable continuous migration
- [ ] disable legacy minting
- [ ] enable BAI and texkey minting
- [ ] register all BAIs with the script
- [ ] make `edit` links on Literature records point to `/editor/record/literature/{pid_value}`

**Comment by tsgit** [comment]
- seems like there is some specific order of operations, e.g.
stop curation `before` final dump 

- minting is record id allocation?
there is some texkey minting going on, too

- is there a reason not to migrate individual crawlers as they become available and instead do it all in bulk?

- switch off legacy HTTPD ? or otherwise make it clear that the data is now `stale`

- modify/remove DNS entry for legacy ? or point to a static page with link to labs?

- switch off the legacy nodes and release the DBOD instance ?

**Comment by michamos** [comment]
>     * seems like there is some specific order of operations, e.g.
>       stop curation `before` final dump

A full dump takes ~10 days AFAIK. Do we really want to stop all curation (and updates?) for that period?



>     * minting is record id allocation?
>       there is some texkey minting going on, too

Indeed, I've added a step for that (and BAIs)

> is there a reason not to migrate individual crawlers as they become available and instead do it all in bulk?

The DESY workflow needs to be migrated completely to labs for that. You're right that it doesn't need to happen simultaneously with switching off legacy, it could be done earlier (that would be a very good idea actually).
